### ISSUE TITLE
show data loading does not work

### ISSUE THREAD

**Issue by mirkomancin** [ptc-iot-sharing/BMCollectionView#16]
although the flag on the SHOW DATA LOADING property is active, the widget being loaded does not display the progress bar

**Comment by BogdanMihaiciuc** [comment]
This is partly a result of collection view's custom method of attaching itself to a mashup, however this was never meant to be supported and was explicitly disabled in the early builds as well. 

The option appears because it's a core widget property that all widgets get regardless of declaring it or not.

As a workaround, you can get the standard progress bar to appear by binding any field in the data set to another widget that supports it or by creating a custom loader using the service start and **ServiceInvokeCompleted** events.
